[tool.poetry]
name = "EchoInStone"
version = "0.1.0"
description = "A tool to extract and transcribe audio."
authors = ["Jean-Jerome Levy"]
packages = [
    { include = "EchoInStone" }
]

[tool.poetry.dependencies]
python = "3.12.*"
feedparser = "^6.0.11"
requests = "^2.32.3"
transformers = "^4.50.0"
torch = {version = "2.7.0", source = "pytorch-xpu"}
pyannote-audio = "^3.3.2"
pydub = "^0.25.1"
accelerate = "^1.3.0"
jinja2 = "^3.1.6"
opencv-python = "^4.13.0.90"
scenedetect = "^0.6.7.1"
pytesseract = "^0.3.13"
paddleocr = "^3.3.3"
paddlepaddle = "^3.3.0"
yt-dlp = "^2026.3.17"
faster-whisper = {version = "^1.1.0", optional = true}
easyocr = {version = "^1.7.2", optional = true}
gigaam = {git = "https://github.com/salute-developers/GigaAM.git", rev = "6e4b027c6fb554e09e8b9059b757a175295ab879", optional = true}

[tool.poetry.extras]
faster-whisper = ["faster-whisper"]
scene-ocr = ["easyocr"]
gigaam = ["gigaam"]

[[tool.poetry.source]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
priority = "supplemental"

[tool.poetry.group.dev.dependencies]
pytest-bdd = "^8.1.0"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
echotranscriber = "main:main"
